export const roleConfig = {
  admin: {
    path: '/admin',
    short: 'ADMIN',
    title: 'Admin Portal',
    cardTitle: 'Admin Portal',
    description: 'For administration, operations and management.',
    cta: 'Login as Admin',
    image: '/images/admin-role.jpg',
    intro: 'Secure access for EVEXIA administration, operations and management.',
    visualTitle: 'Keep the whole picture in view.',
    visualCopy: 'A clear, considered workspace for the people who keep EVEXIA moving.',
  },
  mr: {
    path: '/mr',
    short: 'MR',
    title: 'Medical Representative Portal',
    cardTitle: 'Medical Representative Portal',
    description: 'For medical representatives to access their EVEXIA portal.',
    cta: 'Login as MR',
    image: '/images/mr-role.jpg',
    intro: 'Secure access for EVEXIA medical representatives in the field.',
    visualTitle: 'Bring every conversation forward.',
    visualCopy: 'A focused entry point for the teams connecting science with care.',
  },
  doctor: {
    path: '/doctor',
    short: 'DOCTOR',
    title: 'Doctor Portal',
    cardTitle: 'Doctor Portal',
    description: 'For doctors to access their EVEXIA portal.',
    cta: 'Login as Doctor',
    image: '/images/doctor-role.jpg',
    intro: 'Secure access for doctors and healthcare professionals.',
    visualTitle: 'Make room for better care.',
    visualCopy: 'A calm, direct gateway designed around the pace of modern healthcare.',
  },
};