"""Explicit UI label aliases for safe activity reporting search."""
BROWSER_ACTIONS = {
    "allergen_create": "Allergen product created", "allergen_edit": "Allergen product updated",
    "allergen_status": "Allergen product status changed", "allergen_delete": "Allergen product deleted",
    "opening_balance_create": "Opening balance created", "opening_balance_edit": "Opening balance updated",
    "opening_balance_status": "Opening balance status changed", "opening_balance_delete": "Opening balance deleted",
    "headquarter_create": "Headquarter created", "headquarter_edit": "Headquarter updated",
    "headquarter_status": "Headquarter status changed", "headquarter_delete": "Headquarter deleted",
    "product_category_create": "Product category created", "product_category_edit": "Product category updated",
    "product_category_status": "Product category status changed", "product_category_delete": "Product category deleted",
    "designation_create": "Designation created", "designation_edit": "Designation updated",
    "designation_status": "Designation status changed", "designation_delete": "Designation deleted",
    "vendor_create": "Vendor created", "vendor_edit": "Vendor updated",
    "vendor_status": "Vendor status changed", "vendor_delete": "Vendor deleted",
    "sales_target_create": "Sales target created", "sales_target_edit": "Sales target updated",
    "sales_target_status": "Sales target status changed", "sales_target_delete": "Sales target deleted",
    "role_create": "Role created", "role_update": "Role updated", "role_delete": "Role deleted",
    "role_permissions": "Role permissions changed", "staff_access": "Staff workspace access changed",
    "courier_create": "Courier partner created", "courier_edit": "Courier partner updated",
    "courier_status": "Courier partner status changed", "courier_delete": "Courier partner deleted",
    "staff_create": "Staff created", "staff_update": "Staff updated", "staff_status": "Staff status changed", "staff_delete": "Staff deleted",
    "browser_page_view": "Page visited", "browser_created": "Record created",
    "browser_updated": "Record updated", "browser_deleted": "Record deleted",
    "browser_imported": "Records imported", "browser_exported": "Export generated",
    "browser_settings_changed": "Settings changed",
}
RESOURCE_NAMES = {
    "dashboard": "Dashboard", "zone": "Zone Master", "courier_partner": "Courier Partner",
    "storage_location": "Storage Location", "headquarter": "Headquarter Master", "product_category": "Product Category Master",
    "mr": "MR Master", "doctor": "Doctor Master", "patient": "Patient Master",
    "designation": "Designation Master", "staff": "Staff",
    "allergen": "Allergen Master", "vendor": "Vendor Master", "sales_target": "Sales Target",
    "opening_balance": "Opening Balance", "purchase_order": "Purchase Orders",
    "purchase_received": "Purchase Received", "communication": "Communication Settings",
    "message_template": "Message Templates", "invoice_template": "Invoice Templates",
    "receipt_template": "Receipt Templates", "settings": "Settings",
    "roles_permissions": "Roles & Permissions", "custom_role": "Custom role", "activity_logs": "Sessions & Activity Logs",
    "masters": "Masters",
}
